version: '3'

services:
  frontend:
    build:
      context: ./frontend/webform
      dockerfile: Dockerfile
    ports:
      - '9000:80'
    env_file:
      - .env
        # networks:
        #     - webapp-network