services: 
  prod-teipsum-nginx:
    container_name: prod-teipsum-nginx
    image: nginx:latest
    # ports: ["22443:443"]
    ports: ["22080:80"]
    volumes:
        - ./nginx.prod.conf:/etc/nginx/nginx.conf
        - /etc/letsencrypt/archive/teipsum.store:/etc/nginx/ssl
        - /home/adeployer/secrets/.htpasswd:/etc/nginx/secrets/.htpasswd:ro
    networks: [prod-net]


networks:
  prod-net:
    external: true