services:
  prod-teipsum-nginx:
    container_name: prod-teipsum-nginx
    image: nginx:latest
    ports: 
      - "22081:80"
      - "23443:443"
    volumes:
      - ./nginx.prod.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/live/teipsum.store/fullchain.pem:/etc/nginx/ssl/fullchain.pem:ro
      - /etc/letsencrypt/live/teipsum.store/privkey.pem:/etc/nginx/ssl/privkey.pem:ro
      - /home/adeployer/secrets/.htpasswd:/etc/nginx/secrets/.htpasswd:ro
      - /var/www/teipsum/static:/var/www/teipsum/static:ro
    networks:
      - prod-net

networks:
  prod-net:
    external: true