import React, { createContext, useContext, useState } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

const translations = {
  en: {
    // Header
    home: 'Home',
    store: 'Store',
    about: 'About',
    contact: 'Contact',
    discounts: 'Discounts',
    newCollection: 'New Collection',
    searchPlaceholder: 'Search...',
    
    // Homepage
    heroTitle: 'Te Ipsum',
    heroSubtitle: 'Vestments for the Inner Dialogue',
    discoverProducts: 'Discover products',
    shopNowButton: 'Shop Now',
    aboutOurShop: 'About our shop',
    thoughtfulClothing: 'Thoughtful clothing for the inner dialogue.',
    minimalSymbolic: 'Minimal, symbolic, and made for self-expression.',
    
    // About Page
    aboutTitle: 'About Us - Our Sustainable Fashion Story',
    ourStory: 'Our Story',
    thePhilosophy: 'The Philosophy',
    sustainability: 'Sustainability',
    community: 'Community',
    futureVision: 'Future Vision',
    
    // Contact Page
    contactTitle: 'Contact Us - Get in Touch',
    getInTouch: 'Get in Touch',
    contactSubtitle: "We'd love to hear from you! Send us a message and we'll respond as soon as possible.",
    ourStoreLocations: 'Our Store Locations',
    searchStores: 'Search for store locations...',
    name: 'Name',
    email: 'Email',
    message: 'Message',
    sendMessage: 'Send Message',
    sending: 'Sending...',
    
    // Store Page
    storeTitle: 'Store - TeIpsum',
    gridView: 'Grid View',
    listView: 'List View',
    sortByName: 'Sort by Name',
    sortByPrice: 'Sort by Price',
    sortByRating: 'Sort by Rating',
    sortByNewest: 'Sort by Newest',
    productsFound: 'products found',
    noProductsFound: 'No products found',
    tryAdjustingFilters: 'Try adjusting your filters or search terms to find what you\'re looking for.',
    
    // Blog Page
    blogTitle: 'Fashion Blog - Trends, Tips & Sustainability',
    allPosts: 'All Posts',
    fashion: 'Fashion',
    styleTips: 'Style Tips',
    companyNews: 'Company News',
    trends: 'Trends',
    readMore: 'Read More',
    loadMoreArticles: 'Load More Articles',
    
    // Footer
    shippingInfo: 'Shipping Info',
    returnsExchanges: 'Returns & Exchanges',
    newArrivals: 'New Arrivals',
    cookiePolicy: 'Cookie Policy',
    faq: 'FAQ',
    bestsellers: 'Bestsellers',
    sizeGuide: 'Size Guide',
    sustainabilityFooter: 'Sustainability',
    accessibility: 'Accessibility',
    privacyPolicy: 'Privacy Policy',
    termsOfService: 'Terms of Service',
    careers: 'Careers',
    blog: 'Blog',
    language: 'Language',
    theme: 'Theme',
    lightTheme: 'Light Theme',
    darkTheme: 'Dark Theme',
    customerService: 'Customer Service',
    company: 'Company',
    newsletter: 'Newsletter',
    stayUpdated: 'Stay updated with our latest collections and exclusive offers.',
    emailPlaceholder: 'Enter your email address',
    subscribe: 'Subscribe',
    allRightsReserved: 'All rights reserved',
    allProducts: 'All Products',
    
    // Common & Forms
    loading: 'Loading...',
    error: 'Error',
    previous: 'Previous',
    next: 'Next',
    page: 'Page',
    of: 'of',
    close: 'Close',
    open: 'Open',
    save: 'Save',
    cancel: 'Cancel',
    
    // Form pages
    registerTitle: 'Create Account',
    registerSubtitle: 'Join TeIpsum and discover your style',
    loginTitle: 'Sign In',
    loginSubtitle: 'Sign in to your account to continue',
    firstName: 'First Name',
    lastName: 'Last Name',
    dateOfBirth: 'Date of Birth',
    emailAddress: 'Email Address',
    phoneNumber: 'Phone Number',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    createAccount: 'Create Account',
    signIn: 'Sign In',
    creatingAccount: 'Creating Account...',
    signingIn: 'Signing In...',
    firstNamePlaceholder: 'Enter your first name',
    lastNamePlaceholder: 'Enter your last name',
    phonePlaceholder: 'Enter your phone number',
    passwordPlaceholder: 'Create a strong password',
    confirmPasswordPlaceholder: 'Confirm your password',
    selectBirthDate: 'Select your birth date',
    alreadyHaveAccount: 'Already have an account?',
    dontHaveAccount: "Don't have an account?",
    createOne: 'Create one',
    forgotPassword: 'Forgot your password?',

    
    // Store pages
    newCollectionTitle: 'New Collection 2025',
    newCollectionSubtitle: 'Discover the latest trends and innovative designs',
    bestsellersTitle: 'Our Bestsellers',
    bestsellersSubtitle: 'Discover the most loved pieces by our customers',
    discountsTitle: 'Special Offers',
    discountsSubtitle: 'Discover amazing deals on our premium collection',
    upTo: 'Up to',
    off: 'OFF',
    justLaunched: 'JUST LAUNCHED',
    newItems: 'New Items',
    categories: 'Categories',
    allCategories: 'All Categories',
    allGenders: 'All Genders',
    men: 'Men',
    women: 'Women',
    unisex: 'Unisex',
    sortBy: 'Sort by',
    sortByDiscount: 'Sort by Discount',
    clearFilters: 'Clear Filters',
    errorLoading: 'Error loading',
    continueShopping: 'Continue Shopping',
    backToHome: 'Back to Home',
    under: 'Under',
    anyPrice: 'Any Price',
    
    // Checkout & Orders
    checkoutTitle: 'Complete Your Order',
    orderSummary: 'Order Summary',
    items: 'Items',
    shipping: 'Shipping',
    tax: 'Tax',
    total: 'Total',
    orderConfirmed: 'Order Confirmed!',
    thankYouOrder: 'Thank you for your order!',
    orderNumber: 'Order Number',
    orderDate: 'Order Date',
    estimatedDelivery: 'Estimated Delivery',
    paymentMethod: 'Payment Method',
    orderStatus: 'Order Status',
    processing: 'Processing',
    shipped: 'Shipped',
    delivered: 'Delivered',
    noOrdersYet: 'No orders yet',
    startShopping: 'Start shopping to see your order history here',
    welcomeBonus: '🎁 Welcome Bonus',
    welcomeBonusText: 'Join our community and enjoy exclusive benefits with your first order!',
    discount10: '10% off your first order',
    exclusiveVouchers: 'Exclusive vouchers and discounts',
    orderHistory: 'Order history and tracking',
    earlyAccess: 'Early access to new collections',
    personalizedRecs: 'Personalized recommendations',
    freeShipping: 'Free shipping on orders over $100',
    address: 'Address',
    city: 'City',
    postalCode: 'Postal Code',
    country: 'Country',
    orderNotes: 'Order Notes',
    placeOrder: 'Place Order',
    processingOrder: 'Processing Order...',
    
    // Info pages
    ourPhilosophy: 'The Philosophy',
    sustainabilityTitle: 'Sustainability',
    accessibilityTitle: 'Accessibility Statement',
    careersTitle: 'Join Our Team',
    shippingTitle: 'Shipping Information',
    returnsTitle: 'Returns & Exchanges',
    privacyTitle: 'Privacy Policy',
    termsTitle: 'Terms of Service',
    cookieTitle: 'Cookie Policy',
    faqTitle: 'Frequently Asked Questions',
    searchFAQ: 'Search for answers...',
    allQuestions: 'All Questions',
    ordering: 'Ordering',
    returns: 'Returns',
    sizing: 'Sizing',
    care: 'Product Care',
    account: 'Account',
    sizeGuideTitle: 'Size Guide',
    howToMeasure: 'How to Measure',
    fittingTips: 'Fitting Tips',
    needHelp: 'Need Help?',
    personalSizingHelp: 'Our customer service team is trained to help you find the perfect fit',
    lastUpdated: 'Last updated',
    
    // Admin
    adminTitle: 'Product Management',
    addProduct: '+ Add Product',
    manageProducts: 'Manage Products',
    manageUsers: 'Manage Users',
    createAdminUser: 'Create Admin User',
    manageRoles: 'Manage Roles',
    viewAllOrders: 'View All Orders',
    salesAnalytics: 'Sales Analytics',
    generateReports: 'Generate Reports',
    productManagement: 'Product Management',
    userManagement: 'User Management',
    orderManagement: 'Order Management',
    myProfile: 'My Profile',
    welcomeBack: 'Welcome back',
    profileSettings: 'Profile Settings',
    adminPanel: 'Admin Panel',
    
    // FeaturedCollection
    featuredCollectionsTitle: 'Featured Collections',
    featuredCollectionsSubtitle: 'Curated pieces that define modern elegance and timeless style',
    minimalistEssentialsTitle: 'Minimalist Essentials',
    minimalistEssentialsDesc: 'Clean lines and timeless designs that speak to your inner aesthetic. Each piece crafted with intention and purpose.',
    urbanSophisticationTitle: 'Urban Sophistication',
    urbanSophisticationDesc: 'Modern silhouettes for the contemporary soul. Versatile pieces that transition seamlessly from day to night.',
    artisanCollectionTitle: 'Artisan Collection',
    artisanCollectionDesc: 'Handcrafted details and unique textures. Limited pieces that celebrate individual expression and artistry.',
    fromPrice: 'From',
    viewCollection: 'View Collection',
    explore: 'Explore',
    discoverYourStyle: 'Discover Your Style',
    exploreThoughtfulDesigns: 'Explore our complete range of thoughtfully designed pieces',
    shopAllCollections: 'All Collections',

    // SummerCollection
    summer2025Collection: 'Summer 2025 Collection',
    discoverSustainableFashion: 'Discover our latest sustainable fashion pieces',
    womensCollection: 'Women\'s Collection',
    mensCollection: 'Men\'s Collection',
    premiumLine: 'Premium Line',
    lightBrightTitle: 'Light, Bright, Effortlessly You',
    lightBrightDesc: 'Embrace summer in style with flowing silhouettes, earthy tones, and breathable fabrics designed for warm days and cool nights. Our sustainable approach ensures every piece is both beautiful and environmentally conscious.',
    timelessEleganceTitle: 'Timeless Elegance, Modern Comfort',
    timelessEleganceDesc: 'Discover our signature pieces that blend classic sophistication with contemporary comfort, perfect for any occasion. Each garment is meticulously crafted with attention to detail and sustainable practices.',
    ecoFriendlyMaterials: 'Eco-Friendly Materials',
    breathableFabrics: 'Breathable Fabrics',
    timelessDesign: 'Timeless Design',
    premiumQuality: 'Premium Quality',
    perfectFit: 'Perfect Fit',
    versatileStyle: 'Versatile Style',
    discoverCollection: 'Discover Collection',
    readyToRefresh: 'Ready to Refresh Your Wardrobe?',
    exploreCompleteCollection: 'Explore our complete collection and find your perfect style',

    preStore: {
      title: 'Choose Your Style',
      subtitle: 'Select your preferred collection to explore our curated fashion items',
      mensTitle: "Men's Collection",
      mensDescription: "Discover sophisticated styles for the modern gentleman",
      womensTitle: "Women's Collection",
      womensDescription: "Explore elegant designs for the contemporary woman",
      kidsTitle: "Kids' Collection",
      kidsDescription: "Adorable and comfortable clothing for little ones"
    },

    // Validation errors
    validation: {
      requiredField: 'This field is required',
      invalidEmail: 'Please enter a valid email address',
      invalidPhone: 'Please enter a valid phone number',
      passwordTooWeak: 'Password must be at least 8 characters with uppercase, lowercase, number and special character',
      passwordsDontMatch: 'Passwords do not match',
      invalidDateOfBirth: 'Please select a valid date of birth',
      tooYoung: 'You must be at least 13 years old',
      tooManyAttempts: 'Too many registration attempts. Please try again later',
      emailExists: 'A user with this email already exists',
      registrationFailed: 'Registration failed. Please try again'
    },
    
    // Special labels
    welcome: 'Welcome',
    welcomeToTeIpsum: 'Welcome to TeIpsum!',
    accountCreated: 'Your account has been created successfully. You can now sign in to access your profile.',
    signInNow: 'Sign In Now',
    edit: 'Edit',
    delete: 'Delete',
    view: 'View',
    details: 'Details',
    availability: 'Availability',
    inStock: 'In Stock',
    outOfStock: 'Out of Stock',
    addToCart: 'Add to Cart',
    viewDetails: 'View Details',
    filter: 'Filter',
    reset: 'Reset',
    apply: 'Apply',
    search: 'Search',
    results: 'Results'
  },
  
  de: {
    // Header
    home: 'Startseite',
    store: 'Shop',
    about: 'Über uns',
    contact: 'Kontakt',
    discounts: 'Rabatte',
    newCollection: 'Neue Kollektion',
    searchPlaceholder: 'Suchen...',
    
    // Homepage
    heroTitle: 'Te Ipsum',
    heroSubtitle: 'Kleidung für den inneren Dialog',
    discoverProducts: 'Produkte entdecken',
    shopNowButton: 'Jetzt einkaufen',
    aboutOurShop: 'Über unseren Shop',
    thoughtfulClothing: 'Durchdachte Kleidung für den inneren Dialog.',
    minimalSymbolic: 'Minimal, symbolisch und für Selbstausdruck gemacht.',
    
    // About Page
    aboutTitle: 'Über uns - Unsere nachhaltige Mode-Geschichte',
    ourStory: 'Unsere Geschichte',
    thePhilosophy: 'Die Philosophie',
    sustainability: 'Nachhaltigkeit',
    community: 'Gemeinschaft',
    futureVision: 'Zukunftsvision',
    
    // Contact Page
    contactTitle: 'Kontakt - In Verbindung treten',
    getInTouch: 'Kontakt aufnehmen',
    contactSubtitle: 'Wir würden gerne von Ihnen hören! Senden Sie uns eine Nachricht und wir antworten so schnell wie möglich.',
    ourStoreLocations: 'Unsere Filialen',
    searchStores: 'Nach Filialen suchen...',
    name: 'Name',
    email: 'E-Mail',
    message: 'Nachricht',
    sendMessage: 'Nachricht senden',
    sending: 'Wird gesendet...',
    
    // Store Page
    storeTitle: 'Shop - TeIpsum',
    gridView: 'Rasteransicht',
    listView: 'Listenansicht',
    sortByName: 'Nach Name sortieren',
    sortByPrice: 'Nach Preis sortieren',
    sortByRating: 'Nach Bewertung sortieren',
    sortByNewest: 'Nach Neueste sortieren',
    productsFound: 'Produkte gefunden',
    noProductsFound: 'Keine Produkte gefunden',
    tryAdjustingFilters: 'Versuchen Sie, Ihre Filter oder Suchbegriffe anzupassen.',
    
    // Blog Page
    blogTitle: 'Mode-Blog - Trends, Tipps & Nachhaltigkeit',
    allPosts: 'Alle Beiträge',
    fashion: 'Mode',
    styleTips: 'Style-Tipps',
    companyNews: 'Unternehmensnews',
    trends: 'Trends',
    readMore: 'Weiterlesen',
    loadMoreArticles: 'Weitere Artikel laden',
    
    // Footer
    shippingInfo: 'Versandinfo',
    returnsExchanges: 'Rücksendungen & Umtausch',
    newArrivals: 'Neuankömmlinge',
    cookiePolicy: 'Cookie-Richtlinie',
    faq: 'FAQ',
    bestsellers: 'Bestseller',
    sizeGuide: 'Größentabelle',
    sustainabilityFooter: 'Nachhaltigkeit',
    accessibility: 'Barrierefreiheit',
    privacyPolicy: 'Datenschutzrichtlinie',
    termsOfService: 'Nutzungsbedingungen',
    careers: 'Karriere',
    blog: 'Blog',
    language: 'Sprache',
    theme: 'Thema',
    lightTheme: 'Helles Thema',
    darkTheme: 'Dunkles Thema',
    customerService: 'Kundenservice',
    company: 'Unternehmen',
    newsletter: 'Newsletter',
    stayUpdated: 'Bleiben Sie mit unseren neuesten Kollektionen und exklusiven Angeboten auf dem Laufenden.',
    emailPlaceholder: 'Geben Sie Ihre E-Mail-Adresse ein',
    subscribe: 'Abonnieren',
    allRightsReserved: 'Alle Rechte vorbehalten',
    allProducts: 'Alle Produkte',
    
    // Common & Forms
    loading: 'Laden...',
    error: 'Fehler',
    previous: 'Vorherige',
    next: 'Nächste',
    page: 'Seite',
    of: 'von',
    close: 'Schließen',
    open: 'Öffnen',
    save: 'Speichern',
    cancel: 'Abbrechen',
    
    // Form pages
    registerTitle: 'Konto erstellen',
    registerSubtitle: 'Treten Sie TeIpsum bei und entdecken Sie Ihren Stil',
    loginTitle: 'Anmelden',
    loginSubtitle: 'Melden Sie sich in Ihrem Konto an, um fortzufahren',
    firstName: 'Vorname',
    lastName: 'Nachname',
    dateOfBirth: 'Geburtsdatum',
    emailAddress: 'E-Mail-Adresse',
    phoneNumber: 'Telefonnummer',
    password: 'Passwort',
    confirmPassword: 'Passwort bestätigen',
    createAccount: 'Konto erstellen',
    signIn: 'Anmelden',
    creatingAccount: 'Konto wird erstellt...',
    signingIn: 'Anmeldung...',
    firstNamePlaceholder: 'Vornamen eingeben',
    lastNamePlaceholder: 'Nachnamen eingeben',
    phonePlaceholder: 'Telefonnummer eingeben',
    passwordPlaceholder: 'Ein starkes Passwort erstellen',
    confirmPasswordPlaceholder: 'Passwort bestätigen',
    selectBirthDate: 'Geburtsdatum auswählen',
    alreadyHaveAccount: 'Bereits ein Konto?',
    dontHaveAccount: 'Noch kein Konto?',
    createOne: 'Erstellen Sie eines',
    forgotPassword: 'Passwort vergessen?',
    or: 'oder',
    
    // Store pages
    newCollectionTitle: 'Neue Kollektion 2025',
    newCollectionSubtitle: 'Entdecken Sie die neuesten Trends und innovativen Designs',
    bestsellersTitle: 'Unsere Bestseller',
    bestsellersSubtitle: 'Entdecken Sie die beliebtesten Stücke unserer Kunden',
    discountsTitle: 'Sonderangebote',
    discountsSubtitle: 'Entdecken Sie erstaunliche Angebote für unsere Premium-Kollektion',
    upTo: 'Bis zu',
    off: 'RABATT',
    justLaunched: 'GERADE ERSCHIENEN',
    newItems: 'Neue Artikel',
    categories: 'Kategorien',
    allCategories: 'Alle Kategorien',
    allGenders: 'Alle Geschlechter',
    men: 'Herren',
    women: 'Damen',
    unisex: 'Unisex',
    sortBy: 'Sortieren nach',
    sortByDiscount: 'Nach Rabatt sortieren',
    clearFilters: 'Filter löschen',
    errorLoading: 'Fehler beim Laden',
    continueShopping: 'Weiter einkaufen',
    backToHome: 'Zurück zur Startseite',
    under: 'Unter',
    anyPrice: 'Beliebiger Preis',
    
    // Checkout & Orders
    checkoutTitle: 'Bestellung abschließen',
    orderSummary: 'Bestellübersicht',
    items: 'Artikel',
    shipping: 'Versand',
    tax: 'Steuer',
    total: 'Gesamt',
    orderConfirmed: 'Bestellung bestätigt!',
    thankYouOrder: 'Vielen Dank für Ihre Bestellung!',
    orderNumber: 'Bestellnummer',
    orderDate: 'Bestelldatum',
    estimatedDelivery: 'Voraussichtliche Lieferung',
    paymentMethod: 'Zahlungsmethode',
    orderStatus: 'Bestellstatus',
    processing: 'In Bearbeitung',
    shipped: 'Versendet',
    delivered: 'Geliefert',
    noOrdersYet: 'Noch keine Bestellungen',
    startShopping: 'Beginnen Sie mit dem Einkaufen, um Ihre Bestellhistorie hier zu sehen',
    welcomeBonus: '🎁 Willkommensbonus',
    welcomeBonusText: 'Treten Sie unserer Community bei und genießen Sie exklusive Vorteile bei Ihrer ersten Bestellung!',
    discount10: '10% Rabatt auf Ihre erste Bestellung',
    exclusiveVouchers: 'Exklusive Gutscheine und Rabatte',
    orderHistory: 'Bestellverlauf und Tracking',
    earlyAccess: 'Früher Zugang zu neuen Kollektionen',
    personalizedRecs: 'Personalisierte Empfehlungen',
    freeShipping: 'Kostenloser Versand bei Bestellungen über 100€',
    address: 'Adresse',
    city: 'Stadt',
    postalCode: 'Postleitzahl',
    country: 'Land',
    orderNotes: 'Bestellhinweise',
    placeOrder: 'Bestellung aufgeben',
    processingOrder: 'Bestellung wird verarbeitet...',
    
    // Info pages
    ourPhilosophy: 'Die Philosophie',
    sustainabilityTitle: 'Nachhaltigkeit',
    accessibilityTitle: 'Barrierefreiheitserklärung',
    careersTitle: 'Unserem Team beitreten',
    shippingTitle: 'Versandinformationen',
    returnsTitle: 'Rücksendungen & Umtausch',
    privacyTitle: 'Datenschutzrichtlinie',
    termsTitle: 'Nutzungsbedingungen',
    cookieTitle: 'Cookie-Richtlinie',
    faqTitle: 'Häufig gestellte Fragen',
    searchFAQ: 'Nach Antworten suchen...',
    allQuestions: 'Alle Fragen',
    ordering: 'Bestellung',
    returns: 'Rücksendungen',
    sizing: 'Größe',
    care: 'Produktpflege',
    account: 'Konto',
    sizeGuideTitle: 'Größenführer',
    howToMeasure: 'So messen Sie',
    fittingTips: 'Anpassungstipps',
    needHelp: 'Brauchen Sie Hilfe?',
    personalSizingHelp: 'Unser Kundenservice-Team ist geschult, Ihnen zu helfen, die perfekte Passform zu finden',
    lastUpdated: 'Zuletzt aktualisiert',
    
    // Admin
    adminTitle: 'Produktverwaltung',
    addProduct: '+ Produkt hinzufügen',
    manageProducts: 'Produkte verwalten',
    manageUsers: 'Benutzer verwalten',
    createAdminUser: 'Admin-Benutzer erstellen',
    manageRoles: 'Rollen verwalten',
    viewAllOrders: 'Alle Bestellungen anzeigen',
    salesAnalytics: 'Verkaufsanalysen',
    generateReports: 'Berichte erstellen',
    productManagement: 'Produktverwaltung',
    userManagement: 'Benutzerverwaltung',
    orderManagement: 'Bestellverwaltung',
    myProfile: 'Mein Profil',
    welcomeBack: 'Willkommen zurück',
    profileSettings: 'Profileinstellungen',
    adminPanel: 'Admin-Bereich',

    // FeaturedCollection
    featuredCollectionsTitle: 'Ausgewählte Kollektionen',
    featuredCollectionsSubtitle: 'Sorgfältig ausgewählte Stücke, die moderne Eleganz und zeitlosen Stil definieren',
    minimalistEssentialsTitle: 'Minimalistische Essentials',
    minimalistEssentialsDesc: 'Klare Linien und zeitlose Designs, die Ihre innere Ästhetik ansprechen. Jedes Stück mit Absicht und Zweck gefertigt.',
    urbanSophisticationTitle: 'Stadt-Chic',
    urbanSophisticationDesc: 'Moderne Silhouetten für die zeitgenössische Seele. Vielseitige Stücke, die nahtlos vom Tag in die Nacht übergehen.',
    artisanCollectionTitle: 'Handwerk & Design',
    artisanCollectionDesc: 'Handgefertigte Details und einzigartige Texturen. Limitierte Stücke, die individuellen Ausdruck und Kunstfertigkeit feiern.',
    fromPrice: 'Ab',
    viewCollection: 'Kollektion anzeigen',
    explore: 'Entdecken',
    discoverYourStyle: 'Entdecken Sie Ihren Stil',
    exploreThoughtfulDesigns: 'Erkunden Sie unser komplettes Sortiment durchdachter Designs',
    shopAllCollections: 'Alle Kollektionen',

    // SummerCollection
    summer2025Collection: 'Sommer 2025 Kollektion',
    discoverSustainableFashion: 'Entdecken Sie unsere neuesten nachhaltigen Mode-Teile',
    womensCollection: 'Damenkollektion',
    mensCollection: 'Herrenkollektion',
    premiumLine: 'Premium-Linie',
    lightBrightTitle: 'Leicht, luftig, unkompliziert schön',
    lightBrightDesc: 'Verbringen Sie den Sommer stilvoll mit fließenden Silhouetten, erdigen Tönen und atmungsaktiven Stoffen für warme Tage und kühle Nächte. Unser nachhaltiger Ansatz stellt sicher, dass jedes Stück sowohl schön als auch umweltbewusst ist.',
    timelessEleganceTitle: 'Zeitlose Eleganz, moderner Komfort',
    timelessEleganceDesc: 'Entdecken Sie unsere Signature Pieces, die klassische Raffinesse mit zeitgenössischem Komfort verbinden - perfekt für jeden Anlass. Jedes Kleidungsstück wird mit Liebe zum Detail und nachhaltigen Praktiken gefertigt.',
    ecoFriendlyMaterials: 'Umweltfreundliche Materialien',
    breathableFabrics: 'Atmungsaktive Stoffe',
    timelessDesign: 'Zeitloses Design',
    premiumQuality: 'Premium-Qualität',
    perfectFit: 'Perfekte Passform',
    versatileStyle: 'Vielseitiger Stil',
    discoverCollection: 'Kollektion entdecken',
    readyToRefresh: 'Bereit, Ihre Garderobe zu erneuern?',
    exploreCompleteCollection: 'Erkunden Sie unsere komplette Kollektion und finden Sie Ihren perfekten Stil',

    preStore: {
      title: 'Entdecke deinen Stil',
      subtitle: 'Wähle deine bevorzugte Kollektion und entdecke unsere sorgfältig ausgewählten Mode-Teile',
      mensTitle: "Herrenkollektion",
      mensDescription: "Entdecke raffinierte Styles für den modernen Gentleman",
      womensTitle: "Damenkollektion",
      womensDescription: "Erkunde elegante Designs für die moderne Frau",
      kidsTitle: "Kindermode",
      kidsDescription: "Bezaubernde und bequeme Kleidung für die Kleinsten"
    },

    // Validation errors
    validation: {
      requiredField: 'Dieses Feld ist erforderlich',
      invalidEmail: 'Bitte geben Sie eine gültige E-Mail-Adresse ein',
      invalidPhone: 'Bitte geben Sie eine gültige Telefonnummer ein',
      passwordTooWeak: 'Passwort muss mindestens 8 Zeichen mit Großbuchstaben, Kleinbuchstaben, Zahl und Sonderzeichen enthalten',
      passwordsDontMatch: 'Passwörter stimmen nicht überein',
      invalidDateOfBirth: 'Bitte wählen Sie ein gültiges Geburtsdatum',
      tooYoung: 'Sie müssen mindestens 13 Jahre alt sein',
      tooManyAttempts: 'Zu viele Registrierungsversuche. Bitte versuchen Sie es später erneut',
      emailExists: 'Ein Benutzer mit dieser E-Mail-Adresse existiert bereits',
      registrationFailed: 'Registrierung fehlgeschlagen. Bitte versuchen Sie es erneut'
    },
    
    // Special labels
    welcome: 'Willkommen',
    welcomeToTeIpsum: 'Willkommen bei TeIpsum!',
    accountCreated: 'Ihr Konto wurde erfolgreich erstellt. Sie können sich jetzt anmelden, um auf Ihr Profil zuzugreifen.',
    signInNow: 'Jetzt anmelden',
    edit: 'Bearbeiten',
    delete: 'Löschen',
    view: 'Anzeigen',
    details: 'Details',
    availability: 'Verfügbarkeit',
    inStock: 'Auf Lager',
    outOfStock: 'Nicht auf Lager',
    addToCart: 'In den Warenkorb',
    viewDetails: 'Details anzeigen',
    filter: 'Filter',
    reset: 'Zurücksetzen',
    apply: 'Anwenden',
    search: 'Suchen',
    results: 'Ergebnisse'
  },
  
  pl: {
    // Header
    home: 'Strona główna',
    store: 'Sklep',
    about: 'O nas',
    contact: 'Kontakt',
    discounts: 'Zniżki',
    newCollection: 'Nowa kolekcja',
    searchPlaceholder: 'Szukaj...',
    
    // Homepage
    heroTitle: 'Te Ipsum',
    heroSubtitle: 'Odzież dla wewnętrznego dialogu',
    discoverProducts: 'Odkryj produkty',
    shopNowButton: 'Kup teraz',
    aboutOurShop: 'O naszym sklepie',
    thoughtfulClothing: 'Przemyślana odzież dla wewnętrznego dialogu.',
    minimalSymbolic: 'Minimalistyczna, symboliczna i stworzona do wyrażania siebie.',
    
    // About Page
    aboutTitle: 'O nas - Nasza historia zrównoważonej mody',
    ourStory: 'Nasza historia',
    thePhilosophy: 'Filozofia',
    sustainability: 'Zrównoważony rozwój',
    community: 'Społeczność',
    futureVision: 'Wizja przyszłości',
    
    // Contact Page
    contactTitle: 'Kontakt - Skontaktuj się z nami',
    getInTouch: 'Skontaktuj się z nami',
    contactSubtitle: 'Chcielibyśmy usłyszeć od Ciebie! Wyślij nam wiadomość, a odpowiemy tak szybko, jak to możliwe.',
    ourStoreLocations: 'Nasze sklepy',
    searchStores: 'Szukaj sklepów...',
    name: 'Imię',
    email: 'E-mail',
    message: 'Wiadomość',
    sendMessage: 'Wyślij wiadomość',
    sending: 'Wysyłanie...',
    
    // Store Page
    storeTitle: 'Sklep - TeIpsum',
    gridView: 'Widok siatki',
    listView: 'Widok listy',
    sortByName: 'Sortuj według nazwy',
    sortByPrice: 'Sortuj według ceny',
    sortByRating: 'Sortuj według oceny',
    sortByNewest: 'Sortuj według najnowszych',
    productsFound: 'produktów znaleziono',
    noProductsFound: 'Nie znaleziono produktów',
    tryAdjustingFilters: 'Spróbuj dostosować filtry lub terminy wyszukiwania.',
    
    // Blog Page
    blogTitle: 'Blog modowy - Trendy, porady i zrównoważony rozwój',
    allPosts: 'Wszystkie posty',
    fashion: 'Moda',
    styleTips: 'Porady stylistyczne',
    companyNews: 'Wiadomości firmy',
    trends: 'Trendy',
    readMore: 'Czytaj więcej',
    loadMoreArticles: 'Załaduj więcej artykułów',
    minRead: 'min. czytania',
    
    // Footer
    shippingInfo: 'Informacje o wysyłce',
    returnsExchanges: 'Zwroty i wymiany',
    newArrivals: 'Nowości',
    cookiePolicy: 'Polityka cookies',
    faq: 'FAQ',
    bestsellers: 'Bestsellery',
    sizeGuide: 'Tabela rozmiarów',
    sustainabilityFooter: 'Zrównoważony rozwój',
    accessibility: 'Dostępność',
    privacyPolicy: 'Polityka prywatności',
    termsOfService: 'Regulamin',
    careers: 'Kariera',
    blog: 'Blog',
    language: 'Język',
    theme: 'Motyw',
    lightTheme: 'Jasny motyw',
    darkTheme: 'Ciemny motyw',
    customerService: 'Obsługa klienta',
    company: 'Firma',
    newsletter: 'Newsletter',
    stayUpdated: 'Zostaw się na bieżąco z naszymi najnowszymi kolekcjami i wyłącznymi ofertami.',
    emailPlaceholder: 'Wprowadź swój adres e-mail',
    subscribe: 'Subskrybuj',
    allRightsReserved: 'Wszystkie prawa zastrzeżone',
    allProducts: 'Wszystkie produkty',
    
    // Common & Forms
    loading: 'Ładowanie...',
    error: 'Błąd',
    previous: 'Poprzednia',
    next: 'Następna',
    page: 'Strona',
    of: 'z',
    close: 'Zamknij',
    open: 'Otwórz',
    save: 'Zapisz',
    cancel: 'Anuluj',
    
    // Form pages
    registerTitle: 'Utwórz konto',
    registerSubtitle: 'Dołącz do TeIpsum i odkryj swój styl',
    loginTitle: 'Zaloguj się',
    loginSubtitle: 'Zaloguj się do swojego konta, aby kontynuować',
    firstName: 'Imię',
    lastName: 'Nazwisko',
    dateOfBirth: 'Data urodzenia',
    emailAddress: 'Adres e-mail',
    phoneNumber: 'Numer telefonu',
    password: 'Hasło',
    confirmPassword: 'Potwierdź hasło',
    createAccount: 'Utwórz konto',
    signIn: 'Zaloguj się',
    creatingAccount: 'Tworzenie konta...',
    signingIn: 'Logowanie...',
    firstNamePlaceholder: 'Wprowadź swoje imię',
    lastNamePlaceholder: 'Wprowadź swoje nazwisko',
    phonePlaceholder: 'Wprowadź swój numer telefonu',
    passwordPlaceholder: 'Utwórz silne hasło',
    confirmPasswordPlaceholder: 'Potwierdź swoje hasło',
    selectBirthDate: 'Wybierz datę urodzenia',
    alreadyHaveAccount: 'Masz już konto?',
    dontHaveAccount: 'Nie masz konta?',
    createOne: 'Utwórz je',
    forgotPassword: 'Zapomniałeś hasła?',
    or: 'lub',
    
    // Store pages
    newCollectionTitle: 'Nowa kolekcja 2025',
    newCollectionSubtitle: 'Odkryj najnowsze trendy i innowacyjne projekty',
    bestsellersTitle: 'Nasze bestsellery',
    bestsellersSubtitle: 'Odkryj najbardziej lubiane produkty naszych klientów',
    discountsTitle: 'Oferty specjalne',
    discountsSubtitle: 'Odkryj niesamowite okazje na naszą premium kolekcję',
    upTo: 'Do',
    off: 'RABAT',
    justLaunched: 'WŁAŚNIE WYSTARTOWAŁO',
    newItems: 'Nowe produkty',
    categories: 'Kategorie',
    allCategories: 'Wszystkie kategorie',
    allGenders: 'Wszystkie płcie',
    men: 'Mężczyźni',
    women: 'Kobiety',
    unisex: 'Unisex',
    sortBy: 'Sortuj według',
    sortByDiscount: 'Sortuj według rabatu',
    clearFilters: 'Wyczyść filtry',
    errorLoading: 'Błąd podczas ładowania',
    continueShopping: 'Kontynuuj zakupy',
    backToHome: 'Powrót do strony głównej',
    under: 'Poniżej',
    anyPrice: 'Dowolna cena',
    
    // Checkout & Orders
    checkoutTitle: 'Zakończ zamówienie',
    orderSummary: 'Podsumowanie zamówienia',
    items: 'Produkty',
    shipping: 'Wysyłka',
    tax: 'Podatek',
    total: 'Razem',
    orderConfirmed: 'Zamówienie potwierdzone!',
    thankYouOrder: 'Dziękujemy za zamówienie!',
    orderNumber: 'Numer zamówienia',
    orderDate: 'Data zamówienia',
    estimatedDelivery: 'Przewidywana dostawa',
    paymentMethod: 'Metoda płatności',
    orderStatus: 'Status zamówienia',
    processing: 'Przetwarzanie',
    shipped: 'Wysłane',
    delivered: 'Dostarczone',
    noOrdersYet: 'Brak zamówień',
    startShopping: 'Zacznij zakupy, aby zobaczyć historię zamówień',
    welcomeBonus: '🎁 Powitalny bonus',
    welcomeBonusText: 'Dołącz do naszej społeczności i ciesz się ekskluzywnymi korzyściami przy pierwszym zamówieniu!',
    discount10: '10% rabatu na pierwsze zamówienie',
    exclusiveVouchers: 'Ekskluzywne vouchery i rabaty',
    orderHistory: 'Historia zamówień i śledzenie',
    earlyAccess: 'Wczesny dostęp do nowych kolekcji',
    personalizedRecs: 'Spersonalizowane rekomendacje',
    freeShipping: 'Darmowa wysyłka przy zamówieniach powyżej 400zł',
    address: 'Adres',
    city: 'Miasto',
    postalCode: 'Kod pocztowy',
    country: 'Kraj',
    orderNotes: 'Uwagi do zamówienia',
    placeOrder: 'Złóż zamówienie',
    processingOrder: 'Przetwarzanie zamówienia...',
    
    // Info pages
    ourPhilosophy: 'Filozofia',
    sustainabilityTitle: 'Zrównoważony rozwój',
    accessibilityTitle: 'Deklaracja dostępności',
    careersTitle: 'Dołącz do naszego zespołu',
    shippingTitle: 'Informacje o wysyłce',
    returnsTitle: 'Zwroty i wymiany',
    privacyTitle: 'Polityka prywatności',
    termsTitle: 'Regulamin',
    cookieTitle: 'Polityka cookies',
    faqTitle: 'Często zadawane pytania',
    searchFAQ: 'Szukaj odpowiedzi...',
    allQuestions: 'Wszystkie pytania',
    ordering: 'Składanie zamówienia',
    returns: 'Zwroty',
    sizing: 'Rozmiar',
    care: 'Pielęgnacja produktu',
    account: 'Konto',
    sizeGuideTitle: 'Przewodnik po rozmiarach',
    howToMeasure: 'Jak mierzyć',
    fittingTips: 'Wskazówki dopasowania',
    needHelp: 'Potrzebujesz pomocy?',
    personalSizingHelp: 'Nasz zespół obsługi klienta jest przeszkolony, aby pomóc Ci znaleźć idealny rozmiar',
    lastUpdated: 'Ostatnia aktualizacja',
    
    // Admin
    adminTitle: 'Zarządzanie produktami',
    addProduct: '+ Dodaj produkt',
    manageProducts: 'Zarządzaj produktami',
    manageUsers: 'Zarządzaj użytkownikami',
    createAdminUser: 'Utwórz użytkownika admina',
    manageRoles: 'Zarządzaj rolami',
    viewAllOrders: 'Zobacz wszystkie zamówienia',
    salesAnalytics: 'Analiza sprzedaży',
    generateReports: 'Generuj raporty',
    productManagement: 'Zarządzanie produktami',
    userManagement: 'Zarządzanie użytkownikami',
    orderManagement: 'Zarządzanie zamówieniami',
    myProfile: 'Mój profil',
    welcomeBack: 'Witamy z powrotem',
    profileSettings: 'Ustawienia profilu',
    adminPanel: 'Panel administratora',
    
    // FeaturedCollection
    featuredCollectionsTitle: 'Wyróżnione Kolekcje',
    featuredCollectionsSubtitle: 'Dobrane kawałki, które definiują nowoczesną elegancję i ponadczasowy styl',
    minimalistEssentialsTitle: 'Minimalistyczne Podstawy',
    minimalistEssentialsDesc: 'Czyste linie i ponadczasowe projekty, które mówią do Twojej wewnętrznej estetyki. Każdy element wykonany z intencją i celem.',
    urbanSophisticationTitle: 'Miejski Styl',
    urbanSophisticationDesc: 'Nowoczesne sylwetki dla współczesnej duszy. Wszechstronne kawałki, które płynnie przechodzą od dnia do nocy.',
    artisanCollectionTitle: 'Kolekcja Autorska',
    artisanCollectionDesc: 'Ręcznie wykonane detale i unikalne faktury. Limitowane kawałki, które celebrują indywidualny wyraz i rzemiosło.',
    fromPrice: 'Od',
    viewCollection: 'Zobacz Kolekcję',
    explore: 'Odkryj',
    discoverYourStyle: 'Odkryj Swój Styl',
    exploreThoughtfulDesigns: 'Odkryj naszą pełną gamę przemyślanych projektów',
    shopAllCollections: 'Wszystkie Kolekcje',

    // SummerCollection
    summer2025Collection: 'Kolekcja Letnia 2025',
    discoverSustainableFashion: 'Odkryj nasze najnowsze zrównoważone elementy mody',
    womensCollection: 'Kolekcja Damska',
    mensCollection: 'Kolekcja Męska',
    premiumLine: 'Linia Premium',
    lightBrightTitle: 'Lekkość, Światło, Naturalny Styl',
    lightBrightDesc: 'Przywitaj lato z stylem dzięki płynnym sylwetkom, ziemistym kolorom i oddychającym tkaninom zaprojektowanym na ciepłe dni i chłodne noce. Nasze podejście do zrównoważonego rozwoju zapewnia, że każdy element jest zarówno piękny, jak i świadomy ekologicznie.',
    timelessEleganceTitle: 'Bezczasowa Elegancja, Nowoczesny Komfort',
    timelessEleganceDesc: 'Odkryj nasze sygnaturowe kawałki, które łączą klasyczną elegancję z nowoczesnym komfortem, idealne na każdą okazję. Każdy element jest starannie wykonany z dbałością o szczegóły i praktyki zrównoważonego rozwoju.',
    ecoFriendlyMaterials: 'Przyjazne dla środowiska materiały',
    breathableFabrics: 'Oddychające tkaniny',
    timelessDesign: 'Bezczasowy design',
    premiumQuality: 'Jakość Premium',
    perfectFit: 'Idealne dopasowanie',
    versatileStyle: 'Wszechstronny styl',
    discoverCollection: 'Odkryj kolekcję',
    readyToRefresh: 'Gotowy odświeżyć swoją garderobę?',
    exploreCompleteCollection: 'Odkryj naszą kompletną kolekcję i znajdź swój idealny styl',

    preStore: {
      title: 'Wybierz swój styl',
      subtitle: 'Wybierz preferowaną kolekcję, aby odkryć nasze starannie dobrane elementy mody',
      mensTitle: "Moda Męska",
      mensDescription: "Odkryj wyrafinowane style dla nowoczesnego dżentelmena",
      womensTitle: "Moda Damska",
      womensDescription: "Odkryj eleganckie projekty dla współczesnej kobiety",
      kidsTitle: "Moda Dziecięca",
      kidsDescription: "Urocze i wygodne ubranka dla najmłodszych"
    },

    // Validation errors
    validation: {
      requiredField: 'To pole jest wymagane',
      invalidEmail: 'Proszę wprowadzić prawidłowy adres e-mail',
      invalidPhone: 'Proszę wprowadzić prawidłowy numer telefonu',
      passwordTooWeak: 'Hasło musi mieć co najmniej 8 znaków z dużymi literami, małymi literami, cyframi i znakami specjalnymi',
      passwordsDontMatch: 'Hasła nie są identyczne',
      invalidDateOfBirth: 'Proszę wybrać prawidłową datę urodzenia',
      tooYoung: 'Musisz mieć co najmniej 13 lat',
      tooManyAttempts: 'Zbyt wiele prób rejestracji. Proszę spróbować później',
      emailExists: 'Użytkownik z tym adresem e-mail już istnieje',
      registrationFailed: 'Rejestracja nie powiodła się. Proszę spróbować ponownie'
    },
    
    // Special labels
    welcome: 'Witamy',
    welcomeToTeIpsum: 'Witamy w TeIpsum!',
    accountCreated: 'Twoje konto zostało pomyślnie utworzone. Możesz się teraz zalogować, aby uzyskać dostęp do swojego profilu.',
    signInNow: 'Zaloguj się teraz',
    edit: 'Edytuj',
    delete: 'Usuń',
    view: 'Zobacz',
    details: 'Szczegóły',
    availability: 'Dostępność',
    inStock: 'Dostępne',
    outOfStock: 'Niedostępne',
    addToCart: 'Dodaj do koszyka',
    viewDetails: 'Zobacz szczegóły',
    filter: 'Filtruj',
    reset: 'Resetuj',
    apply: 'Zastosuj',
    search: 'Szukaj',
    results: 'Wyniki'
  },
  
  ua: {
    // Header
    home: 'Головна',
    store: 'Магазин',
    about: 'Про нас',
    contact: 'Контакти',
    discounts: 'Знижки',
    newCollection: 'Нова колекція',
    searchPlaceholder: 'Пошук...',
    
    // Homepage
    heroTitle: 'Te Ipsum',
    heroSubtitle: 'Одяг для внутрішнього діалогу',
    discoverProducts: 'Відкрийте продукти',
    shopNowButton: 'Купити зараз',
    aboutOurShop: 'Про наш магазин',
    thoughtfulClothing: 'Продуманий одяг для внутрішнього діалогу.',
    minimalSymbolic: 'Мінімалістичний, символічний і створений для самовираження.',
    
    // About Page
    aboutTitle: 'Про нас - Наша історія сталої моди',
    ourStory: 'Наша історія',
    thePhilosophy: 'Філософія',
    sustainability: 'Сталий розвиток',
    community: 'Спільнота',
    futureVision: 'Бачення майбутнього',
    
    // Contact Page
    contactTitle: 'Контакти - Зв\'яжіться з нами',
    getInTouch: 'Зв\'яжіться з нами',
    contactSubtitle: 'Ми б хотіли почути від вас! Надішліть нам повідомлення, і ми відповімо якомога швидше.',
    ourStoreLocations: 'Наші магазини',
    searchStores: 'Пошук магазинів...',
    name: 'Ім\'я',
    fullName: 'Ваше повне ім\'я',
    email: 'Електронна пошта',
    message: 'Повідомлення',
    howWeCanHelp: '',
    sendMessage: 'Надіслати повідомлення',
    sending: 'Надсилання...',
    
    // Store Page
    storeTitle: 'Магазин - TeIpsum',
    gridView: 'Сітка',
    listView: 'Список',
    sortByName: 'Сортувати за назвою',
    sortByPrice: 'Сортувати за ціною',
    sortByRating: 'Сортувати за рейтингом',
    sortByNewest: 'Сортувати за новизною',
    productsFound: 'товарів знайдено',
    price: 'Ціна',
    discount: 'Знижка',
    noProductsFound: 'Товари не знайдено',
    tryAdjustingFilters: 'Спробуйте налаштувати фільтри або умови пошуку.',
    available: 'Доступний',
    notAvailable: 'Недоступний',
    
    // Blog Page
    blogTitle: 'Модний блог - Тренди, поради та сталий розвиток',
    blog: 'Блог',
    allPosts: 'Всі пости',
    fashion: 'Мода',
    styleTips: 'Поради зі стилю',
    companyNews: 'Новини компанії',
    trends: 'Тренди',
    readMore: 'Читати далі',
    loadMoreArticles: 'Завантажити більше статей',
    minRead: 'хв',
    
    // Footer
    shippingInfo: 'Інформація про доставку',
    returnsExchanges: 'Повернення та обміни',
    newArrivals: 'Новинки',
    cookiePolicy: 'Політика cookies',
    faq: 'FAQ',
    bestsellers: 'Бестселери',
    sizeGuide: 'Таблиця розмірів',
    sustainabilityFooter: 'Сталий розвиток',
    accessibility: 'Доступність',
    privacyPolicy: 'Політика конфіденційності',
    termsOfService: 'Умови використання',
    careers: 'Кар\'єра',
    language: 'Мова',
    theme: 'Тема',
    lightTheme: 'Світла тема',
    darkTheme: 'Темна тема',
    customerService: 'Служба підтримки клієнтів',
    company: 'Компанія',
    newsletter: 'Новини',
    stayUpdated: 'Залишайтеся на зв\'язку з нашими найновішими колекціями та виключними пропозиціями.',
    emailPlaceholder: 'Введіть ваш адрес електронної пошти',
    subscribe: 'Підписатися',
    allRightsReserved: 'Всі права захищені',
    allProducts: 'Всі товари',
    
    // Common & Forms
    loading: 'Завантаження...',
    error: 'Помилка',
    previous: 'Попередня',
    next: 'Наступна',
    page: 'Сторінка',
    of: 'з',
    close: 'Закрити',
    open: 'Відкрити',
    save: 'Зберегти',
    cancel: 'Скасувати',
    
    // Form pages
    registerTitle: 'Реєстрація',
    registerSubtitle: 'Приєднуйтесь до TeIpsum і відкрийте свій стиль',
    loginTitle: 'Увійти',
    loginSubtitle: 'Увійдіть до свого облікового запису, щоб продовжити',
    firstName: 'Ім\'я',
    lastName: 'Прізвище',
    dateOfBirth: 'Дата народження',
    emailAddress: 'Адреса електронної пошти',
    phoneNumber: 'Номер телефону',
    password: 'Пароль',
    confirmPassword: 'Підтвердити пароль',
    createAccount: 'Створити обліковий запис',
    signIn: 'Увійти',
    creatingAccount: 'Створення облікового запису...',
    signingIn: 'Вхід...',
    firstNamePlaceholder: 'Введіть своє ім\'я',
    lastNamePlaceholder: 'Введіть своє прізвище',
    phonePlaceholder: 'Введіть свій номер телефону',
    passwordPlaceholder: 'Створіть надійний пароль',
    confirmPasswordPlaceholder: 'Підтвердьте свій пароль',
    selectBirthDate: 'Виберіть дату народження',
    alreadyHaveAccount: 'Вже маєте обліковий запис?',
    dontHaveAccount: 'Немає облікового запису?',
    createOne: 'Створіть його',
    forgotPassword: 'Забули пароль?',
    or: 'або',
    
    // Store pages
    newCollectionTitle: 'Нова колекція 2025',
    newCollectionSubtitle: 'Відкрийте найновіші тренди та інноваційні дизайни',
    bestsellersTitle: 'Наші бестселери',
    bestsellersSubtitle: 'Відкрийте найулюбленіші товари наших клієнтів',
    discountsTitle: 'Спеціальні пропозиції',
    discountsSubtitle: 'Відкрийте неймовірні пропозиції на нашу преміум колекцію',
    upTo: 'До',
    off: 'ЗНИЖКА',
    justLaunched: 'ЩОСЬ НОВЕ',
    newItems: 'Нові товари',
    categories: 'Категорії',
    allCategories: 'Всі категорії',
    genders: 'Стать',
    allGenders: 'Всі статі',
    all: 'Всі',
    men: 'Чоловіча',
    women: 'Жіноча',
    unisex: 'Унісекс',
    minDiscount: 'Мінімальна знижка',
    sortBy: 'Сортувати за',
    sortByDiscount: 'Сортувати за знижкою',
    continueShopping: 'Продовжити покупки',
    backToHome: 'Повернутися на головну',
    under: 'Під',
    anyPrice: 'Будь-яка ціна',
    clearFilters: 'Очистити фільтри',
    maxPrice: 'Максимальна ціна',
    
    // Checkout & Orders
    checkoutTitle: 'Завершити замовлення',
    orderSummary: 'Підсумок замовлення',
    items: 'Товари',
    shipping: 'Доставка',
    tax: 'Податок',
    total: 'Разом',
    orderConfirmed: 'Замовлення підтверджено!',
    thankYouOrder: 'Дякуємо за ваше замовлення!',
    orderNumber: 'Номер замовлення',
    orderDate: 'Дата замовлення',
    estimatedDelivery: 'Очікувана доставка',
    paymentMethod: 'Спосіб оплати',
    orderStatus: 'Статус замовлення',
    processing: 'Обробляється',
    shipped: 'Відправлено',
    delivered: 'Доставлено',
    noOrdersYet: 'Ще немає замовлень',
    startShopping: 'Почніть покупки, щоб побачити історію замовлень',
    welcomeBonus: '🎁 Вітальний бонус',
    welcomeBonusText: 'Приєднуйтесь до нашої спільноти та насолоджуйтеся ексклюзивними перевагами при першому замовленні!',
    discount10: '10% знижки на перше замовлення',
    exclusiveVouchers: 'Ексклюзивні ваучери та знижки',
    orderHistory: 'Історія замовлень та відстеження',
    earlyAccess: 'Ранній доступ до нових колекцій',
    personalizedRecs: 'Персоналізовані рекомендації',
    freeShipping: 'Безкоштовна доставка при замовленнях від 4000 грн',
    address: 'Адреса',
    city: 'Місто',
    postalCode: 'Поштовий індекс',
    country: 'Країна',
    orderNotes: 'Примітки до замовлення',
    placeOrder: 'Оформити замовлення',
    processingOrder: 'Обробка замовлення...',
    
    // Info pages
    ourPhilosophy: 'Філософія',
    sustainabilityTitle: 'Сталий розвиток',
    accessibilityTitle: 'Декларація доступності',
    careersTitle: 'Приєднуйтесь до нашої команди',
    shippingTitle: 'Інформація про доставку',
    returnsTitle: 'Повернення та обміни',
    privacyTitle: 'Політика конфіденційності',
    termsTitle: 'Умови використання',
    cookieTitle: 'Політика cookies',
    faqTitle: 'Часті питання',
    searchFAQ: 'Пошук відповідей...',
    allQuestions: 'Всі питання',
    ordering: 'Замовлення',
    returns: 'Повернення',
    sizing: 'Розмір',
    care: 'Догляд за продуктом',
    account: 'Обліковий запис',
    sizeGuideTitle: 'Посібник з розмірів',
    howToMeasure: 'Як вимірювати',
    fittingTips: 'Поради щодо підбору',
    needHelp: 'Потрібна допомога?',
    personalSizingHelp: 'Наша команда обслуговування клієнтів навчена допомагати вам знайти ідеальний розмір',
    lastUpdated: 'Останнє оновлення',
    
    // Admin
    adminTitle: 'Управління продуктами',
    addProduct: '+ Додати продукт',
    manageProducts: 'Керувати продуктами',
    manageUsers: 'Керувати користувачами',
    createAdminUser: 'Створити адміністратора',
    manageRoles: 'Керувати ролями',
    viewAllOrders: 'Переглянути всі замовлення',
    salesAnalytics: 'Аналіз продажів',
    generateReports: 'Генерувати звіти',
    productManagement: 'Управління продуктами',
    userManagement: 'Управління користувачами',
    orderManagement: 'Управління замовленнями',
    myProfile: 'Мій профіль',
    welcomeBack: 'Ласкаво просимо назад',
    profileSettings: 'Налаштування профілю',
    adminPanel: 'Панель адміністратора',
    
    // FeaturedCollection
    featuredCollectionsTitle: 'Вибрані Колекції',
    featuredCollectionsSubtitle: 'Відібрані речі, які визначають сучасну елегантність і безчасовий стиль',
    minimalistEssentialsTitle: 'Мінімалістичні Основи',
    minimalistEssentialsDesc: 'Чисті лінії та незабутні дизайни, які підкреслюють вашу внутрішню естетику. Кожен предмет створений з наміром та метою.',
    urbanSophisticationTitle: 'Міський Шик',
    urbanSophisticationDesc: 'Сучасні силуети для сучасної душі. Універсальні речі, які плавно переходять від дня до ночі.',
    artisanCollectionTitle: 'Авторська Колекція',
    artisanCollectionDesc: 'Ручна робота та унікальні текстури. Лімітовані речі, які святкують індивідуальність та майстерність.',
    fromPrice: 'Від',
    viewCollection: 'Переглянути Колекцію',
    explore: 'Дослідити',
    discoverYourStyle: 'Відкрийте Свій Стиль',
    exploreThoughtfulDesigns: 'Дослідьте наш повний асортимент продуманих речей',
    shopAllCollections: 'Всі Колекції',

    // SummerCollection
    summer2025Collection: 'Літня Колекція 2025',
    discoverSustainableFashion: 'Відкрийте наші найновіші елементи сталої моди',
    womensCollection: 'Жіноча Колекція',
    mensCollection: 'Чоловіча Колекція',
    premiumLine: 'Преміум Лінія',
    lightBrightTitle: 'Легкість, Світло, Натуральний Стиль',
    lightBrightDesc: 'Зустріньте літо зі стилем завдяки пливким силуетам, землистим тонам та дихаючим тканинам, розробленим для теплих днів та прохолодних ночей. Наш підхід до сталого розвитку гарантує, що кожен елемент є одночасно красивим та екологічно свідомим.',
    timelessEleganceTitle: 'Витончена Елегантність, Сучасний Комфорт',
    timelessEleganceDesc: 'Відкрийте наші фірмові речі, які поєднують класичну витонченість із сучасним комфортом, ідеально підходять для будь-якої нагоди. Кожен елемент ретельно виготовлений з увагою до деталей та практик сталого розвитку.',
    ecoFriendlyMaterials: 'Екологічні матеріали',
    breathableFabrics: 'Дихаючі тканини',
    timelessDesign: 'Позачасовий дизайн',
    premiumQuality: 'Преміум якість',
    perfectFit: 'Ідеальна посадка',
    versatileStyle: 'Універсальний стиль',
    discoverCollection: 'Відкрити колекцію',
    readyToRefresh: 'Готові оновити свій гардероб?',
    exploreCompleteCollection: 'Дослідьте нашу повну колекцію та знайдіть свій ідеальний стиль',

    preStore: {
      title: 'Обери свій стиль',
      subtitle: 'Виберіть бажану колекцію, щоб відкрити наші ретельно відібрані елементи моди',
      mensTitle: "Чоловіча Мода",
      mensDescription: "Відкрий витончені стилі для сучасного джентльмена",
      womensTitle: "Жіноча Мода",
      womensDescription: "Досліджуй елегантні дизайни для сучасної жінки",
      kidsTitle: "Дитяча Мода",
      kidsDescription: "Чарівний та зручний одяг для маленьких"
    },

    // Validation errors
    validation: {
      requiredField: 'Це поле є обов\'язковим',
      invalidEmail: 'Будь ласка, введіть дійсну адресу електронної пошти',
      invalidPhone: 'Будь ласка, введіть дійсний номер телефону',
      passwordTooWeak: 'Пароль повинен містити щонайменше 8 символів з великими літерами, малими літерами, цифрами та спеціальними символами',
      passwordsDontMatch: 'Паролі не збігаються',
      invalidDateOfBirth: 'Будь ласка, виберіть дійсну дату народження',
      tooYoung: 'Ви повинні бути щонайменше 13 років',
      tooManyAttempts: 'Забагато спроб реєстрації. Будь ласка, спробуйте пізніше',
      emailExists: 'Користувач з цією електронною адресою вже існує',
      registrationFailed: 'Реєстрація не вдалася. Будь ласка, спробуйте ще раз'
    },
    
    // Special labels
    welcome: 'Ласкаво просимо',
    welcomeToTeIpsum: 'Ласкаво просимо до TeIpsum!',
    accountCreated: 'Ваш обліковий запис було успішно створено. Тепер ви можете увійти, щоб отримати доступ до свого профілю.',
    signInNow: 'Увійти зараз',
    edit: 'Редагувати',
    delete: 'Видалити',
    view: 'Переглянути',
    details: 'Деталі',
    availability: 'Доступність',
    inStock: 'В наявності',
    outOfStock: 'Немає в наявності',
    addToCart: 'Додати до кошика',
    viewDetails: 'Переглянути деталі',
    filter: 'Фільтр',
    reset: 'Скинути',
    apply: 'Застосувати',
    search: 'Пошук',
    results: 'Результати'
  }
};

export const LanguageProvider = ({ children }) => {
  const [currentLanguage, setCurrentLanguage] = useState(() => {
    const savedLanguage = localStorage.getItem('teipsum-language');
    return savedLanguage || 'en';
  });

  const changeLanguage = (language) => {
    setCurrentLanguage(language);
    localStorage.setItem('teipsum-language', language);
  };

  const t = (key) => {
    return translations[currentLanguage]?.[key] || translations.en[key] || key;
  };

  const value = {
    currentLanguage,
    changeLanguage,
    t,
    availableLanguages: [
      { code: 'en', name: 'English', flag: '🇺🇸' },
      { code: 'de', name: 'Deutsch', flag: '🇩🇪' },
      { code: 'pl', name: 'Polski', flag: '🇵🇱' },
      { code: 'ua', name: 'Українська', flag: '🇺🇦' }
    ]
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}; 