CREATE DATABASE <<AUTH_SERVICE_DB_NAME>>;
CREATE DATABASE <<USER_SERVICE_DB_NAME>>;
CREATE DATABASE <<ADMIN_PRODUCT_SERVICE_DB_NAME>>;
CREATE DATABASE <<CATALOG_SERVICE_DB_NAME>>;
CREATE DATABASE <<ORDER_SERVICE_DB_NAME>>;

CREATE USER <<AUTH_SERVICE_DB_USER>>     WITH ENCRYPTED PASSWORD '<<AUTH_SERVICE_DB_PASSWORD>>';
CREATE USER <<USER_SERVICE_DB_USER>>     WITH ENCRYPTED PASSWORD '<<USER_SERVICE_DB_PASSWORD>>';
CREATE USER <<ADMIN_PRODUCT_SERVICE_DB_USER>>  WITH ENCRYPTED PASSWORD '<<ADMIN_PRODUCT_SERVICE_DB_PASSWORD>>';
CREATE USER <<CATALOG_SERVICE_DB_USER>>  WITH ENCRYPTED PASSWORD '<<CATALOG_SERVICE_DB_PASSWORD>>';
CREATE USER <<ORDER_SERVICE_DB_USER>>    WITH ENCRYPTED PASSWORD '<<ORDER_SERVICE_DB_PASSWORD>>';

GRANT ALL PRIVILEGES ON DATABASE <<AUTH_SERVICE_DB_NAME>>     TO <<AUTH_SERVICE_DB_USER>>;
GRANT ALL PRIVILEGES ON DATABASE <<USER_SERVICE_DB_NAME>>     TO <<USER_SERVICE_DB_USER>>;
GRANT ALL PRIVILEGES ON DATABASE <<ADMIN_PRODUCT_SERVICE_DB_NAME>>  TO <<ADMIN_PRODUCT_SERVICE_DB_USER>>;
GRANT ALL PRIVILEGES ON DATABASE <<CATALOG_SERVICE_DB_NAME>>  TO <<CATALOG_SERVICE_DB_USER>>;
GRANT ALL PRIVILEGES ON DATABASE <<ORDER_SERVICE_DB_NAME>>    TO <<ORDER_SERVICE_DB_USER>>;