\connect <<AUTH_SERVICE_DB_NAME>>
GRANT USAGE, CREATE ON SCHEMA public TO <<AUTH_SERVICE_DB_USER>>;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO <<AUTH_SERVICE_DB_USER>>;

\connect <<USER_SERVICE_DB_NAME>>
GRANT USAGE, CREATE ON SCHEMA public TO <<USER_SERVICE_DB_USER>>;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO <<USER_SERVICE_DB_USER>>;

\connect <<CATALOG_SERVICE_DB_NAME>>
GRANT USAGE, CREATE ON SCHEMA public TO <<CATALOG_SERVICE_DB_USER>>;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO <<CATALOG_SERVICE_DB_USER>>;

\connect <<ADMIN_PRODUCT_SERVICE_DB_NAME>>
GRANT USAGE, CREATE ON SCHEMA public TO <<ADMIN_PRODUCT_SERVICE_DB_USER>>;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO <<ADMIN_PRODUCT_SERVICE_DB_USER>>;

\connect <<ORDER_SERVICE_DB_NAME>>
GRANT USAGE, CREATE ON SCHEMA public TO <<ORDER_SERVICE_DB_USER>>;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO <<ORDER_SERVICE_DB_USER>>;
