CREATE DATABASE <<AUTH_SERVICE_DB_NAME>>;
CREATE DATABASE <<USER_SERVICE_DB_NAME>>;
CREATE DATABASE <<PRODUCT_SERVICE_DB_NAME>>;
CREATE DATABASE <<ORDER_SERVICE_DB_NAME>>;

CREATE USER <<AUTH_SERVICE_DB_USER>>     WITH ENCRYPTED PASSWORD '<<AUTH_SERVICE_DB_PASSWORD>>';
CREATE USER <<USER_SERVICE_DB_USER>>     WITH ENCRYPTED PASSWORD '<<USER_SERVICE_DB_PASSWORD>>';
CREATE USER <<PRODUCT_SERVICE_DB_USER>>  WITH ENCRYPTED PASSWORD '<<PRODUCT_SERVICE_DB_PASSWORD>>';
CREATE USER <<ORDER_SERVICE_DB_USER>>    WITH ENCRYPTED PASSWORD '<<ORDER_SERVICE_DB_PASSWORD>>';

GRANT ALL PRIVILEGES ON DATABASE <<AUTH_SERVICE_DB_NAME>>     TO <<AUTH_SERVICE_DB_USER>>;
GRANT ALL PRIVILEGES ON DATABASE <<USER_SERVICE_DB_NAME>>     TO <<USER_SERVICE_DB_USER>>;
GRANT ALL PRIVILEGES ON DATABASE <<PRODUCT_SERVICE_DB_NAME>>  TO <<PRODUCT_SERVICE_DB_USER>>;
GRANT ALL PRIVILEGES ON DATABASE <<ORDER_SERVICE_DB_NAME>>    TO <<ORDER_SERVICE_DB_USER>>;
