FROM maven:3.9.11-eclipse-temurin-17-alpine AS builder

WORKDIR /app

COPY pom.xml ./backend/pom.xml
COPY shared-dto/pom.xml ./backend/shared-dto/pom.xml
COPY shared-dto/src ./backend/shared-dto/src

RUN mvn -f shared-dto/pom.xml install -DskipTests -Dparent.relativePath=../pom.xml
