name: Reusable Update Docs

on:
  workflow_call:
    inputs:
      DEPLOY_ENV:
        required: true
        type: string
    secrets:
      PROJECT_DIR:
        required: true
      SSH_HOST:
        required: true
      SSH_USER:
        required: true
      SSH_KEY:
        required: true
      DEPLOY_PORT:
        required: true

jobs:
  update-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update docs via SSH
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.DEPLOY_PORT }}
          script: |
            set -e
            cd ${{ secrets.PROJECT_DIR }}/docs
            chmod +x collect-specs.sh
            ./collect-specs.sh
            docker compose down --remove-orphans
            docker compose build --no-cache
            docker compose up -d