name: Reusable Update Docs

on:
  workflow_call:
    inputs:
      DEPLOY_ENV:
        required: true
        type: string
    secrets:
      PROJECT_DIR:
        required: true
      SSH_HOST:
        required: true
      SSH_USER:
        required: true
      SSH_KEY:
        required: true
      DEPLOY_PORT:
        required: true

jobs:
  update-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update docs via SSH
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.DEPLOY_PORT }}
          script: |
            set -e
            
            echo "📦 Updating docs..."
            cd ${{ secrets.PROJECT_DIR }}/docs
            chmod +x collect-specs.sh

            echo "🔄 Collecting specs..."
            ./collect-specs.sh

            echo "🔄 Rebuilding docs container..."
            docker compose -f docker-compose.docs.yml down --remove-orphans
            docker compose -f docker-compose.docs.yml build --no-cache
            docker compose -f docker-compose.docs.yml up -d